### ISSUE TITLE
Missing ResponseMapper in the readme.md

### ISSUE THREAD

**Issue by cyrilgandon** [n1ru4l/graphql-schema-generator-rest#34]
Just to be extra confident about my code.

In the V2 breaking changes log, there is:

`@rest(…, mapper: …)` must be changed to `@rest(…, responseMapper: …)`.

But in the code, there is no mention of a `responseMapper` option in the `rest` directive. My guess is that it is missing in the doc.

**Comment by n1ru4l** [comment]
Yeah seems like it is missing 😅, could you please create a pull request to add it?

**Comment by n1ru4l** [comment]
Fixed by #36
